ECG_COLUMNS = [
    "ecg_id", "patient_id", "age", "sex", "height", "weight", "nurse", "site", "device",
    "recording_date","report","scp_codes","heart_axis","infarction_stadium1",
    "infarction_stadium2","validated_by","second_opinion","initial_autogenerated_report",
    "validated_by_human","baseline_drift","static_noise","burst_noise","electrodes_problems",
    "extra_beats","pacemaker","strat_fold","filename_lr","filename_hr"
]


DATASET_REGISTRY = {
    "patient_csv": {
        "label": "ECG Dataset",
        "description": "Electrocardiogram recordings and patient metadata",
        "columns": [
            "id", "ecg_id", "age", "sex", "height", "weight",
            "nurse", "site", "device", "recording_date",
            "heart_axis", "strat_fold", "filename_lr", "filename_hr"
        ]
    },
    "patients": {
        "label": "Patients Personal Data",
        "description": "Dummy personal data for patients",
        "columns": ["id","Phone", "Email", "Address", "Postal_Code", "Country", "Gender", "DOB", "City", "Department"]
    },
    "heart": {
        "label": "Patients Heart Data",
        "description": "Patients Heart Datasets",
        "columns": ["age", "sex", "cp", "trestbps",	"chol",	"fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca",	"thal",	"target"]
    }
}

DATE_COLUMNS = {
    "patients": ["DOB"],
    "patient_csv": ["recording_date"]
}

